### ISSUE TITLE
项目启动不了

### ISSUE THREAD

**Issue by lyc152** [SeeSharply/LearnAngular#1]
ng serve 报错 LearnAngular git:(master) ✗ ng serve
The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (/Users/petter/Documents/workspace/private/angular-action/LearnAngular/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

**Comment by SeeSharply** [comment]
your problem is ：package was not properly installed；
try npm install before you  use ng serve；
你的问题是有些node包没有正确安装，先使用npm install 命令，然后再用ng serve；
